### ISSUE TITLE
Binary POST, or check URL option

### ISSUE THREAD

**Issue by alexgleason** [steelcityamir/safe-content-ai#2]
Hello. 👋 I came across this while looking for a way to block porn on a decentralized social media project I'm building.

I would have a list of URLs that I want to check, and not necessarily have the file yet, so doing a POST of the entire file would be inconvenient. If I could pass a URL that would be better.

Another possible solution is that I can fetch the file and stream it to the API so I don't need to load the whole file into memory at once. But in that case `/upload` should accept raw binary data and a content-type of image/jpg.

**Comment by steelcityamir** [comment]
Hey Alex!  I agree supporting a list of image URLs would be a useful feature.   I will implement this before the end of the month and update this issue.
