### ISSUE TITLE
Deployment fails on Platforms like Railway 

### ISSUE THREAD

**Issue by shishantbiswas** [steelcityamir/safe-content-ai#4]
Hi there,

Deploying it on render.com causes to hit the ram limit and on railway.app I get a bunch of warning and errors show below 
![Screenshot_20240718_163017](https://github.com/user-attachments/assets/50d22982-ffe8-48fb-a136-755d946d236c)

I used the docker image and forked the repo and build from there as well, also tried it on my local machine and such error do occur and some additional stuff is downloaded and cached but it does work as mentioned in usage, this is where my railway deployment crashed all the time

**Comment by steelcityamir** [comment]
Hi @shishantbiswas, I was able to reproduce the issue.  It appears that you need to give it more memory to run in Railway.

<img width="635" alt="image" src="https://github.com/user-attachments/assets/38036780-7c91-4eb5-ac34-2aceaf02ca88">

**Comment by shishantbiswas** [comment]
I used the free instance on render.com and railway.app only render showed me the error in the console about the lack of memory I'll try running an instance with more memory later, thank you @steelcityamir
